# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 661f52b2225f1e02eefc57a25920312eedb230a6304833e7e7f9271dcf4f42ecf09d74649113a863142ef364ae018aa0f30c12dcf3340705beb21379e2e58e54

test:
  secret_key_base: 0dd2b0af9d78d0f8d319752791a4521cef35ad6ae19504815657bd4d22f705f7d7fdbe87f04f91a422701f97d7d19d9d5e17b36562d52e97896d5be1f1943ce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
